version: '3'

services:
  nodeapp:
    container_name: pmo-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4500:4500"
    # depends_on:
    #   - mongodb
    #   - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
  # redis
  # redis:
  #   image: redis:6.2-alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - '6379:6379'

  # #mongodb database
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_DATABASE=test
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #   command: [--auth]
  #   volumes:
  #     # named volumes
  #     - mongodb:/data/db
  #     - mongoconfig:/data/configdb
  #     - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
# volumes:
#   # default dir on Ubuntu: /var/lib/docker/volumes
#   mongodb:
#   mongoconfig: