export const parastatalsListBeginningWithLagos = [
  'Agent for Mass Communication',
  'Aids Control Agency (LSACA)',
  'Blood Transfusion Committee',
  'Fire Services',
  'Public Advice Center',
  'Office of the Public Defender',
  'Residents Registration Agency (LASRRA)',
  'Emergency Management Agency (LASEMA)',
  'Employment Trust Fund',
  'Public Works Corporation (PWC)',
  'Office for Disability Affairs',
  'Environmental Sanitation and Special Offences Agency(Taskforce)',
  'Scholarship Board',
  'Infrastructure Asset Management Agency',
  'Safety Commission',
  'Vocational Education Board (LASTVEB)',
  'Neighborhood Safety Agency',
  'Pension Commission (LASPEC)',
  'Health Management Agency (LASHMA)',
  'Muslim Pilgrims Welfare Board',
  'Christian Pilgrims Welfare Board',
  'College of Health Technology',
  'Center for Rural Development (CERUD)',
  'Records and Achive Bureau (LASRAB)',
  'Public Procurement Agency (LSPPA)',
  'Physical Planning and Permit Authority (LASPPPA)',
  'Ferry Services (LAGFERRY)',
  'Building Control Agency (LASBCA)',
  'Examination Board',
  'Film and Video Censor Board',
  'Water Regulatory Commission',
  'Urnab Renewal Authority (LASURA)',
  'Number Plate Production Authority',
  'Agricultural Input Supply Development Authority (LAISA)',
  'Mortgage Board (LAGOSHOMS)',
  'Environmental Protection Agency (LASEPA)',
  'Printing Corporation',
  'Parks and Gardens (LASPARK)',
  'Development and Property Corporation (LSDPC)',
  'Health Facilities Monitoring and Accreditation Agency (HEFAMAA)',
  'Transport Management Authority (LASTMA)',
  'Consumer Protection Agency',
  'Materials Testing',
  'Tradition Medicine Board',
  'Corporative College',
  'Waterways Authority (LASWA)',
  'Agricultural Land Holdings Authority (LSALHA)',
  'Coconut Development Authority (LASCODA)',
  'Agricultural Development Auhtority (LASADA)',
  'Waste Management Authority (LAWMA)',
  'Water Corporation (LWC)',
  'Wastewater Management Office',
  'Electricity Board',
  'Drivers Institute (LASDRI)',
  'Council for Arts and Culture',
  'University College of Medicine (LASUCOM)',
  'University Teaching Hospital (LASUTH)',
  'Planning and Environmental Monitoring Authority (LASPEMA)',
  'University (LASU)',
  'Polytechnic (LASPOTECH)',
  'College of Nursing/Midwifery',
  'Universal Basic Education Board (SUBEB)',
  'Public Service Club',
  'Sports Trust Fund',
  'Environmental Sanitation Corp',
  'Women Development Center',
  'Security Trust Fund',
  'Law Enforcement Training Institute',
  'Real Estate Regulatory Authority (LASRERA)',
  'Library Board',
  'Sports Commission',
  'Wharf Landing Fees Collecting Authority',
  'Lotteries Board (LSLB)',
  'Internal Revenue Service (LIRS)',
  'Infrastructure Management and Regulatory Authority (LASIMRA)',
  'Signage and Advertisement Agency (LASAA)',
  'Parking Authority',
];

export const parastatalsListWithoutLagos = [
  'Multi-Door Court House',
  'Citizens Mediation Center',
  'Office of surveyor General',
  'Education Quality Assurance',
  'Public Service Staff Development Company (PSSDC)',
  'Ibile Broadband',
  'Ibile Oil and Gas Corporation',
  'Lagos Television / LTV 8',
  'Radio Lagos / Eko FM',
  'Lagos Traffic Radio',
  'New Towns Development Authority (NTDA)',
  'Lekki Worldwide Investment Company',
  'Adeniran Ogunsanya College of Education',
  'Michael Otedola College of Primary Education (MOCPED)',
  'Office of Administrator-General and Public Trustee',
  'Law Reforms Commission',
  'Office of Resilience',
  'Domestic Violence and Sexual Abuse',
  'Lekki Concession (LCCI)',
  'Ibile Holdings Limited (IHL)',
  'Motor Vehicle Adminstration Agency (MHAA)',
  'Lagos Bus Services Limited (LBSL)',
  'Lagos Metropolitan Area Transport Authority (LAMATA)',
];
