export const parastatalsListBeginningWithLagos = [
  'Agent for Mass Communication',
  'Aids Control Agency (LSACA)',
  'Blood Transfusion Committee',
  'Fire Services',
  'Public Advice Center',
  'Office of the Public Defender',
  'Residents Registration Agency (LASRRA)',
  'Emergency Management Agency (LASEMA)',
  'Employment Trust Fund',
  'Public Works Corporation (PWC)',
  'Office for Disability Affairs',
  'Environmental Sanitation and Special Offences Agency(Taskforce)',
  'Scholarship Board',
  'Infrastructure Asset Management Agency',
  'Safety Commission',
  'Vocational Education Board (LASTVEB)',
  'Neighborhood Safety Agency',
  'Pension Commission (LASPEC)',
  'Health Management Agency (LASHMA)',
  'Muslim Pilgrims Welfare Board',
  'Christian Pilgrims Welfare Board',
  'College of Health Technology',
  'Center for Rural Development (CERUD)',
  'Records and Achive Bureau (LASRAB)',
  'Public Procurement Agency (LSPPA)',
  'Physical Planning and Permit Authority (LASPPPA)',
  'Ferry Services (LAGFERRY)',
  'Building Control Agency (LASBCA)',
  'Examination Board',
  'Film and Video Censor Board',
  'Water Regulatory Commission',
  'Urnab Renewal Authority (LASURA)',
  'Number Plate Production Authority',
  'Agricultural Input Supply Development Authority (LAISA)',
  'Mortgage Board (LAGOSHOMS)',
  'Environmental Protection Agency (LASEPA)',
  'Printing Corporation',
  'Parks and Gardens (LASPARK)',
  'Development and Property Corporation (LSDPC)',
  'Health Facilities Monitoring and Accreditation Agency (HEFAMAA)',
  'Transport Management Authority (LASTMA)',
  'Consumer Protection Agency',
  'Materials Testing',
  'Tradition Medicine Board',
  'Corporative College',
  'Waterways Authority (LASWA)',
  'Agricultural Land Holdings Authority (LSALHA)',
  'Coconut Development Authority (LASCODA)',
  'Agricultural Development Auhtority (LASADA)',
  'Waste Management Authority (LAWMA)',
  'Water Corporation (LWC)',
  'Wastewater Management Office',
  'Electricity Board',
  'Drivers Institute (LASDRI)',
  'Council for Arts and Culture',
  'University College of Medicine (LASUCOM)',
  'University Teaching Hospital (LASUTH)',
  'Planning and Environmental Monitoring Authority (LASPEMA)',
  'University (LASU)',
  'Polytechnic (LASPOTECH)',
  'College of Nursing/Midwifery',
  'Universal Basic Education Board (SUBEB)',
  'Public Service Club',
  'Sports Trust Fund',
  'Environmental Sanitation Corp',
  'Women Development Center',
  'Security Trust Fund',
  'Law Enforcement Training Institute',
  'Real Estate Regulatory Authority (LASRERA)',
  'Library Board',
  'Sports Commission',
  'Wharf Landing Fees Collecting Authority',
  'Lotteries Board (LSLB)',
  'Internal Revenue Service (LIRS)',
  'Infrastructure Management and Regulatory Authority (LASIMRA)',
  'Signage and Advertisement Agency (LASAA)',
  'Parking Authority',
];

export const parastatalsListWithoutLagos = [
  'Multi-Door Court House',
  'Citizens Mediation Center',
  'Office of surveyor General',
  'Education Quality Assurance',
  'Public Service Staff Development Company (PSSDC)',
  'Ibile Broadband',
  'Ibile Oil and Gas Corporation',
  'Lagos Television / LTV 8',
  'Radio Lagos / Eko FM',
  'Lagos Traffic Radio',
  'New Towns Development Authority (NTDA)',
  'Lekki Worldwide Investment Company',
  'Adeniran Ogunsanya College of Education',
  'Michael Otedola College of Primary Education (MOCPED)',
  'Office of Administrator-General and Public Trustee',
  'Law Reforms Commission',
  'Office of Resilience',
  'Domestic Violence and Sexual Abuse',
  'Lekki Concession (LCCI)',
  'Ibile Holdings Limited (IHL)',
  'Motor Vehicle Adminstration Agency (MHAA)',
  'Lagos Bus Services Limited (LBSL)',
  'Lagos Metropolitan Area Transport Authority (LAMATA)',
];

export const parastatalsWithThemes = [
  {
    theme: 'Parastatal Monitoring',
    data: ['Parastatal Monitoring Office'],
    departments: ['Inspectorate', 'Monitoring', 'Research'],
  },
  {
    theme: 'Traffic Management and Transportation',
    data: [
      'Lagos Metropolitan Area Transport Authority (LAMATA)',
      'Lagos State Traffic Management Authority (LASTMA)',
      'Lagos State Bus Services Limited (LBSL)',
      'Lagos State Ferry Services (LAGFERRY)',
      'Lagos State Number Plate Authority',
      'Lagos State Drivers Institute (LASDRI)',
      'Motor Vehicle Administration Agency (MVAA)',
      'Lekki Concession (LCCI)',
      'Lagos State Waterways Authority (LASWA)',
      'Lagos State Parking Permit Authority',
    ],
  },
  {
    theme: 'Health and Environment',
    data: [
      'Lagos State Aids Control Agency (LSACA)',
      'Lagos State Blood Transfusion Committee',
      'Lagos State Environmental Sanitation & Special Offences Agency (Taskforce)',
      'Lagos State Environmental Sanitation Corp',
      'Lagos Waste Management Authority (LAWMA)',
      'Lagos Water Corporation (LWC)',
      'Lagos State Wastewater Management Office',
      'Lagos State Planning & Environmental Monitoring Authority',
      'Lagos State Physical Planning & Permit Authority (LASPPPA)',
      'Lagos State Building Control Agency (LASBCA)',
      'Lagos State Water Regulatory Commission',
      'Lagos State Environmental Protection Agency (LASEPA)',
      'Lagos State Parks & Gardens (LASPARK)',
      'Lagos State Health Facilities Monitoring & Accreditation Agency (HEFAMAA)',
      'Lagos State Infrastructure Maintenance & Regulatory Agency (LASIMRA)',
      'Lagos State Signage & Advertisement Agency (LASAA)',
      'Lagos State Health Management Agency (LASHMA)',
      'Lagos State Materials Testing',
      'Lagos State Traditional Medicine Board',
      'Lagos State Planning & Environmental Monitoring Authority (LASPEMA)',
      'Lagos State University Teaching Hospital',
    ],
  },
  {
    theme: 'Education and Technology',
    data: [
      'Lagos State Scholarship Board',
      'Lagos State Vocational Education Board (LASTVEB)',
      'Lagos State Universal Basic Education Board (SUBEB)',
      'Lagos State Women Development Centre (WDC)',
      'Lagos State University College of Medicine',
      'Lagos State University (LASU)',
      'Adeniran Ogunsanya College of Education/University of Education',
      'Lagos State Polytechnic/LS University of Science and Technology',
      'Michael Otedola College of Primary Education (MOCPED)/University of Education, Epe campus',
      'Lagos State College of Nursing',
      'Lagos State College of Health Technology',
      'Lagos State Centre for Rural Development (CERUD)',
      'Lagos State Examination Board',
      'Lagos State Agency for Mass Education',
      'Office of Education Quality Assurance',
      'Public Service Staff Development Company (PSSDC)',
      'Lagos State Library Board',
      'Lateef Jakande Leadership Academy',
    ],
  },
  {
    theme: 'Making Lagos a 21st Century Economy',
    data: [
      'Lagos State Employment Trust Fund',
      'Lagos State Infrastructure Asset Management Agency',
      'Lagos State Electricity Board',
      'New Towns Development Authority (NTDA)',
      'Lekki Worldwide Investment Company',
      'Lagos State Public Procurement Agency',
      'Lagos State Urban Renewal Authority (LASURA)',
      'Lagos State Development & Property Corporation (LSDPC)',
      'Ibile Holdings Limited (IHL)',
      'Office of Resilience',
      'Lagos State Real Estate Regulatory Authority (LASRERA)',
      'Lagos State Consumer Protection Agency (LASCOPA)',
      'Lagos State Cooperative College',
      'Ibile Broadband',
    ],
  },
  {
    theme: 'Entertainment and Tourism',
    data: [
      'Lagos State Lotteries Board (LSLB)',
      'LagosTelevision/LTV',
      'Radio Lagos/EKO FM',
      'Lagos Traffic Radio',
      'Lagos State Council for Art and Culture',
      'Lagos State Sports Commission',
      'Lagos State Public Service Club',
      'Lagos Sports Trust Fund',
      'Lagos State Records & Archives Bureau (LASRAB)',
      'Lagos State Film & Video Censor Board',
    ],
  },
  {
    theme: 'Security and Governance',
    data: [
      'Lagos State Fire and Rescue Services',
      'Multi-Door Court House',
      "Citizens' Mediation Centre (CMC)",
      'Lagos State Office of the Public Defender',
      'Lagos State Residents Registration Agency (LASRRA)',
      'Lagos State Office for Disability Affairs',
      'Lagos State Safety Commission',
      'Lagos State Neighborhood Safety Agency',
      'Lagos State Pension Commission(LASPEC)',
      'Lagos State Security Trust Fund',
      'Lagos State Agricultural Land Holdings Authority (LSALHA)',
      'Lagos State Coconut Development Authority (LASCODA)',
      'Lagos State Agricultural Development Authority (LASADA)',
      'Ibile Oil & Gas Corporation',
      'Lagos State Agricultural Input Supply Development Authority (LAISA)',
      'Lagos State Printing Corporation',
      'Lagos State Wharf Landing Fees Collecting Authority',
      'Lagos State Internal Revenue Service (LIRS)',
      'Office of Administrator-General & Public Trustee',
      'Lagos State Muslim Pilgrims Welfare Board',
      'Lagos State Christian Pilgrims Welfare Board',
      'Law Reforms Commission',
      'Lagos State Law Enforcement Training Institute (LETI)',
      'Domestic Violence & Sexual Abuse',
      'Lagos Mortgage Board(LagosHoms)',
    ],
  },
  {
    theme: 'General Hospitals',
    data: [
      'Amuwo-Odofin General Hospital APAPA/AMUWO-ODOFIN',
      'Ajeromi General Hospital APAPA/AMUWO-ODOFIN',
      'Apapa General Hospital APAPA/AMUWO-ODOFIN',
      'Gbagada General Hospital GBAGADA/SHOMOLU',
      'Shomolu General Hospital GBAGADA/SHOMOLU',
      'Epe General Hospital EPE/IBEJU-LEKKI',
      'Alimosho General Hospital IGANDO/OJO',
      'Ibeju-Lekki General Hospital EPE/IBEJU-LEKKI',
      'Badagry General Hospital BADAGRY',
      'Ikorodu General Hospital IKORODU',
      'Agbowa General Hospital IKORODU',
      'Ijede Health Centre IKORODU',
      'Lagos Island General Hospital LAGOS ISLAND',
      'Lagos Island Maternity Hospital LAGOS ISLAND',
      'Onikan Health Centre LAGOS ISLAND',
      'Mainland Hospital MAINLAND/YABA',
      'Ebute-Mette Health Centre MAINLAND/YABA',
      'Harvey Road Health Centre MAINLAND/YABA',
      "Massey Street Children's Hospital LAGOS ISLAND 20.Isolo General Hospital MUSHIN/ISOLO",
      'Mushin General Hospital MUSHIN/ISOLO 22.Surulere General Hopital',
      'Orile Agege General Hopital',
      'Ketu/Ejinrin Health centre',
      'Ifako/Ijaiye General Hopital',
      'Eti Osa Matanal and Child Care',
    ],
  },
];
